# nixpacks.toml
nixPkgs = ["python39", "opencv", "mesa", "mesa_glu", "libglvnd", "libglvnd.dev", "libx11", "libxext", "libxrender"]

[phases.build]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "pip uninstall opencv-python",
  "pip install opencv-python-headless"
]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"