# nixpacks.toml
nixPkgs = ["python39", "opencv", "mesa", "mesa_glu", "libglvnd"]

[phases.build]
cmds = [
  "pip install --no-cache-dir -r requirements.txt",
  "apt-get update && apt-get install -y libgl1-mesa-glx"
]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"